categories = [
    "Books",
    "Stationery",
    "Electronics",
    "Accessories",
    "Software",
    "Furniture",
]

item_names = [
    "Notebook",
    "Pen",
    "Pencil",
    "Textbook",
    "Calculator",
    "Laptop",
    "Desk Lamp",
    "Backpack",
    "Chair",
    "Desk",
    "Printer",
    "Highlighter",
    "Binder",
    "Folder",
    "Mouse",
    "Keyboard",
    "USB Drive",
    "Monitor",
    "Whiteboard",
    "Markers",
    "Graphing Calculator",
    "Sticky Notes",
    "Planner",
    "Ruler",
    "Protractor",
    "Scissors",
    "Glue",
    "Tape",
    "Laptop Stand",
    "Headphones",
    "Webcam",
    "Stylus",
    "Tablet",
    "E-Reader",
    "External Hard Drive",
    "Wireless Mouse",
    "Flashcards",
    "Correction Tape",
    "Paper Clips",
    "Stapler",
    "Index Cards",
    "Pencil Case",
    "Desk Organizer",
    "Bullet Journal",
    "Wireless Charger",
    "Smartphone",
    "Tablet Stand",
    "Book Stand",
    "Clip-on Light",
    "Bluetooth Speaker",
    "Digital Pen",
    "Graph Paper",
    "Scientific Calculator",
    "Mechanical Pencil",
    "Colored Pencils",
    "Art Supplies",
    "Drawing Tablet",
    "Smart Notebook",
    "Noise-Canceling Headphones",
    "Laptop Sleeve",
    "Protective Case",
    "Power Bank",
    "Calculator Batteries",
    "Smart Watch",
    "Online Course Subscription",
    "E-Book",
    "Digital Textbook",
    "Classroom Posters",
    "Desk Mat",
    "Pen Holder",
    "Bookends",
    "Laptop Cooler",
    "Surge Protector",
    "Wireless Keyboard",
    "Smart Light Bulb",
    "Cable Organizer",
    "Sticky Flags",
    "Wall Calendar",
    "Desk Calendar",
    "Math Set",
    "Laptop Bag",
    "Wireless Earbuds",
    "Screen Protector",
    "File Cabinet",
    "Bookshelf",
    "Standing Desk",
    "Desk Chair Cushion",
    "Reading Glasses",
    "Ergonomic Chair",
    "Foot Rest",
    "Task Chair",
    "Anti-Glare Screen",
    "Pen Refills",
    "Notebook Refills",
    "Dry Erase Markers",
    "Chalk",
    "Eraser",
    "Digital Planner",
    "Study Timer",
    "Noise Machine",
]

products = [
    {"product_id": 1, "category": "Software", "item": "Pencil", "price": 138.15},
    {"product_id": 2, "category": "Electronics", "item": "Folder", "price": 90.61},
    {"product_id": 3, "category": "Furniture", "item": "Printer", "price": 12.58},
    {"product_id": 4, "category": "Accessories", "item": "Paper Clips", "price": 21.6},
    {"product_id": 5, "category": "Books", "item": "Graph Paper", "price": 31.26},
    {"product_id": 6, "category": "Books", "item": "Wall Calendar", "price": 33.56},
    {"product_id": 7, "category": "Books", "item": "Protective Case", "price": 18.91},
    {"product_id": 8, "category": "Furniture", "item": "Foot Rest", "price": 73.22},
    {
        "product_id": 9,
        "category": "Books",
        "item": "Bluetooth Speaker",
        "price": 136.31,
    },
    {
        "product_id": 10,
        "category": "Books",
        "item": "Smart Light Bulb",
        "price": 129.39,
    },
    {"product_id": 11, "category": "Software", "item": "Digital Pen", "price": 59.54},
    {"product_id": 12, "category": "Furniture", "item": "Calculator", "price": 72.35},
    {"product_id": 13, "category": "Furniture", "item": "Pencil", "price": 13.59},
    {"product_id": 14, "category": "Books", "item": "Protractor", "price": 8.5},
    {
        "product_id": 15,
        "category": "Stationery",
        "item": "Wireless Mouse",
        "price": 142.25,
    },
    {
        "product_id": 16,
        "category": "Electronics",
        "item": "Smart Light Bulb",
        "price": 132.4,
    },
    {"product_id": 17, "category": "Furniture", "item": "Whiteboard", "price": 120.88},
    {
        "product_id": 18,
        "category": "Accessories",
        "item": "Index Cards",
        "price": 149.65,
    },
    {"product_id": 19, "category": "Accessories", "item": "Chair", "price": 75.85},
    {"product_id": 20, "category": "Furniture", "item": "Pen", "price": 31.97},
    {
        "product_id": 21,
        "category": "Accessories",
        "item": "Desk Calendar",
        "price": 55.01,
    },
    {
        "product_id": 22,
        "category": "Software",
        "item": "Wireless Keyboard",
        "price": 31.13,
    },
    {"product_id": 23, "category": "Software", "item": "Standing Desk", "price": 99.3},
    {
        "product_id": 24,
        "category": "Stationery",
        "item": "Desk Organizer",
        "price": 28.94,
    },
    {
        "product_id": 25,
        "category": "Accessories",
        "item": "External Hard Drive",
        "price": 132.35,
    },
    {"product_id": 26, "category": "Accessories", "item": "Stylus", "price": 113.84},
    {
        "product_id": 27,
        "category": "Accessories",
        "item": "Ergonomic Chair",
        "price": 118.97,
    },
    {
        "product_id": 28,
        "category": "Accessories",
        "item": "Wireless Keyboard",
        "price": 26.87,
    },
    {
        "product_id": 29,
        "category": "Electronics",
        "item": "Sticky Flags",
        "price": 36.77,
    },
]
